[remote.github]
owner = "Noai-oss"
repo = "uvg"

[changelog]
header = """
# Changelog

"""
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
        {% if commit.breaking %}[**breaking**] {% endif %}\
        {{ commit.message | upper_first }} - \
        ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
{% endmacro -%}

{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]\
          ({{ self::remote_url() }}/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor %}
    {% for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor -%}
{%- if github -%}
{% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  ## ❤️ New Contributors
{% endif %}\
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
    {%- endif %}
{%- endfor -%}
{%- endif %}


"""
footer = """
<!-- generated by git-cliff -->
"""
trim = true
postprocessors = [
    # Replace the placeholder `<REPO>` with a URL.
    { pattern = "<REPO>", replace = "https://github.com/Noai-oss/uvg" },
]

[git]
conventional_commits = true
filter_unconventional = true
require_conventional = false
split_commits = false
commit_preprocessors = [
  # Remove gitmoji from commit messages, both actual Unicode emoji and :emoji: aliases.
  { pattern = ' *(:\w+:|[\p{Emoji_Presentation}\p{Extended_Pictographic}](?:\u{FE0F})?\u{200D}?) *', replace = "" },
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))" },
]
protect_breaking_commits = false
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->🎉 Features" },
    { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
    { message = "^perf", group = "<!-- 2 -->⚡ Performance" },
    { message = "^refactor", group = "<!-- 3 -->♻️ Refactor" },
    { message = "^build", group = "<!-- 4 -->📦 Build" },
    { message = "^docs", group = "<!-- 5 -->📝 Documentation" },
    { message = "^style", group = "<!-- 6 -->🎨 Styling" },
    { message = "^test", group = "<!-- 7 -->✅ Testing" },
    { message = "^ci", group = "<!-- 8 -->👷 CI" },
    { message = "^chore\\(bot\\)", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(release\\):", skip = true },
    { message = "^chore", group = "<!-- 9 -->🔧 Maintenance" },
    { message = "^revert", group = "<!-- 10 -->⏪ Reverts" },
    { message = ".*", group = "<!-- 11 -->💼 Other" },
]
filter_commits = false
fail_on_unmatched_commit = false
tag_pattern = "v[0-9].*"
link_parsers = []
use_branch_tags = true
topo_order = false
topo_order_commits = true
sort_commits = "oldest"

[bump]
initial_tag = "v0.1.0"
features_always_bump_minor = true
breaking_always_bump_major = false
no_increment_regex = "^build|^chore|^ci|^docs|^style|^test"
