name: Validate PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - labeled

defaults:
  run:
    shell: bash -x -e -u -o pipefail {0}

permissions:
  pull-requests: read

jobs:
  semantic-pull-request:
    if: github.event.action != 'labeled' || github.event.label.name == 'bot-run'
    uses: Noai-oss/CI-templates/.github/workflows/_semantic_pull_request.yml@v0.1.1
